title: Blog posts
description: My Personal Stack Problems
author: Arhdware
github: https://github.com/arhdware
about: Programmer and data science enthusiast.
#disqus_shortname: stackproblems
google_analytics: UA-139026348-1
avatar_url: /static/img/avatar.svg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    #    - icon: fa-facebook
    #      link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/arhdware"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/r-cardo/"
    - icon: fa-stack-exchange
      link: "https://stackoverflow.com/users/11410868/arhdware"
    - icon: fa-github
      link: "https://github.com/arhdware"

share:
    #  twitter_username: github.io
    #fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
      #- text: XML Feed
      #url: /feed.xml

url: "https://arhdwa.re"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

theme: jekyll-theme-minimal